#mariadb:
#    image: mariadb:10
#    restart: always
#    ports:
#        - "3306:3306"
#    environment:
#        - MYSQL_USER=azkaban
#        - MYSQL_PASSWORD=azkaban
#        - MYSQL_DATABASE=azkaban
#        - MYSQL_ROOT_PASSWORD=wootwoot

executor:
    image: cc/azkaban-exec:1.0
    restart: always
    #links:
        #- mariadb

webserver:
    image: cc/azkaban-webserver:1.0
    restart: always
    ports:
        - "4991:8443"
    links:
        - executor:azkaban-executor
       # - mariadb
